previos

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -82,43 +82,28 @@ jobs:
             ./ \
             ${{ vars.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ vars.REMOTE_PATH }}/
 
-      - name: Install dependencies and restart application
-        run: |
-          ssh -o StrictHostKeyChecking=no \
-            ${{ vars.EC2_USER }}@${{ secrets.EC2_HOST }} '
-            set -e # Exit immediately if any command fails
+      # - name: Install dependencies and restart application
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no \
+      #       ${{ vars.EC2_USER }}@${{ secrets.EC2_HOST }} '
+      #       set -e # Exit immediately if any command fails
             
-            cd ${{ vars.REMOTE_PATH }}
+      #       cd ${{ vars.REMOTE_PATH }}
             
-            # Activate virtual environment or create if doesn't exist
-            if [ ! -d "venv" ]; then
-              python3 -m venv venv
-            fi
-            source venv/bin/activate
+      #       # Activate virtual environment or create if doesn't exist
+      #       if [ ! -d "venv" ]; then
+      #         python3 -m venv venv
+      #       fi
+      #       source venv/bin/activate
             
-            # Install/update dependencies
-            pip install --upgrade pip
-            pip install -r requirements.txt
-
-            # Install PM2 if missing
-            if ! command -v pm2 &> /dev/null; then
-              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
-              sudo apt-get install -y nodejs
-              sudo npm install -g pm2
-            fi
-
-            if pm2 list | grep -q "python-app"; then
-              pm2 restart python-app
-            else
-              pm2 start venv/bin/uvicorn --name python-app -- app.main:app --host 0.0.0.0 --port 8000
-            fi
+      #       # Install/update dependencies
+      #       pip install --upgrade pip
+      #       pip install -r requirements.txt
             
-            # Restart application using PM2 (or systemd)
-            # pm2 restart python-app || pm2 start app/main.py --name python-app --interpreter python3
-            pm2 save
+      #       # Restart application using PM2 (or systemd)
+      #       pm2 restart python-app || pm2 start app/main.py --name python-app --interpreter python3
             
-            echo "Deployment commands executed."
-          
+      #       echo "Deployment commands executed."
           
 
       - name: Cleanup
